---
services:
  freqtrade-ai:
    # Use the custom AI image built from our Dockerfile.ai
    build:
      context: .
      dockerfile: "./docker/Dockerfile.ai"
    restart: unless-stopped
    container_name: freqtrade_ai
    # Exposing the environment variables explicitly
    env_file:
      - .env
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade --logfile /freqtrade/user_data/logs/freqtrade_ai.log --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite --config /freqtrade/user_data/config_binance_testnet_spot.json --strategy InformativeSample
