"""
phi_consciousness.py — Phase 26 Sprint 2, Task 12G

IIT Phi (Φ) Metric — "How conscious is this organism?"

Tononi's Integrated Information Theory:
  Φ = information generated by the whole ABOVE the sum of its parts.
  High Φ = modules are deeply integrated, information flows across boundaries.
  Low Φ = modules are isolated, organism is a collection of parts not a whole.

We compute Φ from the organism's actual information flow:
  - Mutual information between modules (from pheromone deposits)
  - Causal influence strength (from causal_engine discoveries)
  - Cross-module attention (from multimodal_encoder)

This is a DIAGNOSTIC metric, not a decision input.
Tracked over time to monitor organism integration health.

Integration:
  - Reads from: pheromone_field, causal_discoveries, organism_audit
  - Writes to: organism_audit (event_type='phi_measurement')
  - Reported in: Telegram weekly summary
"""

import os
import sys
import json
import logging
import math
from datetime import datetime, timezone
from typing import Dict, List, Optional

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
logger = logging.getLogger("phi_consciousness")

from ai_config import AI_DB_PATH
from db import get_db_connection, execute_with_retry, init_db

# Modules to measure integration between
ORGANISM_MODULES = [
    "triple_perception", "evidence_engine", "neural_organism",
    "causal_engine", "counterfactual_engine", "rl_environment",
    "world_model", "dream_engine", "self_model", "active_learner",
    "autonomous_lifecycle", "multimodal_encoder", "cerebellum_timing",
    "order_flow", "market_maker_mode",
]


# Phase 27 Item 8: custom Lempel-Ziv complexity used for the PhiC (Effortful
# Tononi-Christof Compression) approximation. ETC = LZ(combined sequence) −
# Σ LZ(per-module sequence). The library `etcpy` doesn't ship for Python
# 3.13 — this re-implementation is ~30 lines, license-free, and has the
# numerical properties we need (monotone in pattern repetition).
def _lz_complexity(seq: List[int]) -> int:
    """Lempel-Ziv 1976 complexity: number of distinct substrings the LZ parser
    needs to reproduce the sequence. Implemented with a sliding-window scan."""
    if not seq:
        return 0
    n = len(seq)
    i, k, l = 0, 1, 1
    c = 1
    k_max = 1
    while True:
        if k + l > n:
            c += 1
            break
        # Extend match if possible
        if seq[i + k - 1] == seq[k + l - 1]:
            k += 1
            if i + k > n - 1:
                c += 1
                break
        else:
            if k > k_max:
                k_max = k
            i += 1
            if i == l:
                c += 1
                l += k_max
                if l + 1 > n:
                    break
                i = 0
                k = 1
                k_max = 1
            else:
                k = 1
    return c


def _quantize(values: List[float], n_bins: int = 8) -> List[int]:
    """Quantise a continuous activation series into integer tokens for LZ."""
    if not values:
        return []
    arr = np.asarray(values, dtype=float)
    lo, hi = float(arr.min()), float(arr.max())
    if hi - lo < 1e-12:
        return [0] * len(values)
    edges = np.linspace(lo, hi, n_bins + 1)
    return [int(min(n_bins - 1, np.searchsorted(edges, v, side="right") - 1))
            for v in values]


def compute_etc(module_activations: Dict[str, List[float]]) -> float:
    """ETC / PhiC approximation: irreducible-integration measure.

    PhiC = LZ(joint) − Σ LZ(per-module). Normalised to [0, 1] so dashboards
    can show it next to the other Φ components.
    """
    if not module_activations:
        return 0.0
    quantised = {k: _quantize(v) for k, v in module_activations.items() if v}
    if not quantised:
        return 0.0
    combined: List[int] = []
    base_offset = 0
    parts_lz = 0
    for tokens in quantised.values():
        # Offset per module so cross-module patterns are distinguishable
        # from intra-module patterns when concatenated.
        combined.extend(t + base_offset for t in tokens)
        base_offset += 8
        parts_lz += _lz_complexity(tokens)
    whole_lz = _lz_complexity(combined)
    if whole_lz <= 0:
        return 0.0
    return max(0.0, min(1.0, (whole_lz - parts_lz) / whole_lz))


class PhiConsciousness:
    """Integrated Information Theory Φ metric for the trading organism."""

    def __init__(self):
        init_db()

    def compute_phi(self) -> Dict:
        """Compute Φ metric for the current organism state.

        Φ is estimated from:
          1. Causal integration: how many cross-module causal edges exist
          2. Information flow: mutual information from pheromone field activity
          3. Effective connectivity: do module outputs actually influence other modules?

        Returns: {"phi": float, "components": {...}, "interpretation": str}
        """
        components = {}

        # 1. Causal integration — from causal_discoveries table
        causal_phi = self._measure_causal_integration()
        components["causal_integration"] = causal_phi

        # 2. Pheromone flow — information exchange via stigmergy
        pheromone_phi = self._measure_pheromone_flow()
        components["pheromone_flow"] = pheromone_phi

        # 3. Module diversity — are all modules contributing?
        diversity_phi = self._measure_module_diversity()
        components["module_diversity"] = diversity_phi

        # 4. Temporal coherence — do modules evolve together over time?
        temporal_phi = self._measure_temporal_coherence()
        components["temporal_coherence"] = temporal_phi

        # Aggregate Φ (geometric mean of components)
        values = [v for v in components.values() if v > 0]
        if values:
            phi = float(np.exp(np.mean(np.log(np.array(values) + 1e-10))))
        else:
            phi = 0.0

        # Interpretation
        if phi > 0.7:
            interpretation = "HIGHLY_INTEGRATED"
            description = "Organism modules are deeply interconnected — true whole > sum of parts"
        elif phi > 0.4:
            interpretation = "MODERATELY_INTEGRATED"
            description = "Good module interaction but some isolated components"
        elif phi > 0.1:
            interpretation = "LOOSELY_INTEGRATED"
            description = "Modules mostly independent — organism acts as collection of parts"
        else:
            interpretation = "FRAGMENTED"
            description = "Minimal cross-module information flow — not yet an organism"

        result = {
            "phi": round(phi, 4),
            "components": {k: round(v, 4) for k, v in components.items()},
            "interpretation": interpretation,
            "description": description,
            "n_modules": len(ORGANISM_MODULES),
            "measured_at": datetime.now(timezone.utc).isoformat(),
        }

        # Persist
        self._persist_measurement(result)

        logger.info(f"[Phi] Φ = {phi:.4f} ({interpretation})")

        return result

    def _measure_causal_integration(self) -> float:
        """Measure how many cross-module causal edges exist."""
        conn = get_db_connection(AI_DB_PATH)
        try:
            row = conn.execute("""
                SELECT COUNT(*) as n_edges,
                       AVG(causal_strength) as avg_strength
                FROM causal_discoveries
                WHERE is_active = 1
            """).fetchone()

            n_edges = row["n_edges"] or 0
            avg_strength = row["avg_strength"] or 0

            # Max possible edges: N*(N-1) for N modules
            max_edges = len(ORGANISM_MODULES) * (len(ORGANISM_MODULES) - 1)
            edge_ratio = n_edges / max(max_edges, 1)

            # Integration = edge_density × avg_strength
            return float(min(edge_ratio * avg_strength * 10, 1.0))

        except Exception:
            return 0.0
        finally:
            conn.close()

    def _measure_pheromone_flow(self) -> float:
        """Measure information exchange via pheromone field."""
        try:
            from pheromone_field import get_pheromone_field
            pfield = get_pheromone_field()

            # Count active pheromone signals
            active_signals = 0
            for key in ["prediction", "uncertainty", "organism_health",
                        "HORMONE_STATE", "FEAR_LEVEL", "lifecycle_state",
                        "multimodal_fusion", "cerebellum_timing",
                        "exploration_suggestions", "lob_state",
                        "order_flow_state", "mm_state"]:
                val = pfield.read(key)
                if val is not None:
                    active_signals += 1

            # More active signals = more information flow
            return min(active_signals / 12, 1.0)

        except Exception:
            return 0.0

    def _measure_module_diversity(self) -> float:
        """Measure how many different modules are contributing to decisions."""
        conn = get_db_connection(AI_DB_PATH)
        try:
            # Count unique modules in recent organism_audit
            row = conn.execute("""
                SELECT COUNT(DISTINCT event_type) as n_types
                FROM organism_audit
                WHERE timestamp >= datetime('now', '-7 days')
            """).fetchone()

            n_types = row["n_types"] or 0
            # Expect at least 5 different event types for healthy diversity
            return min(n_types / 10, 1.0)

        except Exception:
            return 0.0
        finally:
            conn.close()

    def _measure_temporal_coherence(self) -> float:
        """Measure if modules evolve together over time."""
        conn = get_db_connection(AI_DB_PATH)
        try:
            # Check if multiple modules have recent activity
            rows = conn.execute("""
                SELECT organ, COUNT(*) as cnt
                FROM organ_performance_history
                WHERE timestamp >= datetime('now', '-7 days')
                GROUP BY organ
            """).fetchall()

            if not rows:
                return 0.0

            active_organs = len(rows)
            avg_activity = np.mean([r["cnt"] for r in rows])

            # More co-active organs with balanced activity = higher coherence
            balance = 1.0 - (np.std([r["cnt"] for r in rows]) / (avg_activity + 1e-6))
            coverage = active_organs / max(len(ORGANISM_MODULES), 1)

            return float(min(balance * coverage, 1.0))

        except Exception:
            return 0.0
        finally:
            conn.close()

    def _persist_measurement(self, result: Dict):
        """Write Φ measurement to organism_audit."""
        try:
            execute_with_retry(
                """INSERT INTO organism_audit
                   (timestamp, event_type, details_json)
                   VALUES (datetime('now'), 'phi_measurement', ?)""",
                (json.dumps(result),),
                max_retries=3,
            )
        except Exception:
            pass

    def get_phi_history(self, n: int = 10) -> List[Dict]:
        """Get recent Φ measurements."""
        conn = get_db_connection(AI_DB_PATH)
        try:
            rows = conn.execute("""
                SELECT details_json, timestamp FROM organism_audit
                WHERE event_type = 'phi_measurement'
                ORDER BY timestamp DESC LIMIT ?
            """, (n,)).fetchall()

            history = []
            for row in rows:
                try:
                    data = json.loads(row["details_json"])
                    data["timestamp"] = row["timestamp"]
                    history.append(data)
                except Exception:
                    pass
            return history
        finally:
            conn.close()


# Singleton
_phi_instance = None

def get_phi() -> PhiConsciousness:
    global _phi_instance
    if _phi_instance is None:
        _phi_instance = PhiConsciousness()
    return _phi_instance
